author: Contex
description: Overrides Vanilla ore generation, allowing much more dynamic population of ore and stoof.
main: net.betterverse.oregenchange.OreGenChange
name: OreGenChange
version: '2.0'
